deployment:
  tasks:
    # Updated with your actual username 'donking'
    - export DEPLOYPATH=/home/donking/public_html/
    - echo "Deploying to $DEPLOYPATH"
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    # Install PHP dependencies (tries common composer locations)
    - php composer.phar install --no-dev --optimize-autoloader || composer install --no-dev --optimize-autoloader || true
    # Laravel post-deploy steps (ignore failures if commands aren't available)
    - php artisan migrate --force || true
    - php artisan config:cache || true
    - php artisan route:cache || true
    - php artisan storage:link || true
